# Generated by Django 5.0.3 on 2024-04-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=30)),
                ('Company', models.CharField(max_length=30)),
                ('Rate', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
