# Generated by Django 5.0.3 on 2024-04-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0002_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
