# Generated by Django 5.0.3 on 2024-04-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0002_alter_medicine_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_approved',
            field=models.BooleanField(default=0),
        ),
    ]
