# Generated by Django 5.0.3 on 2024-04-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0003_medicine_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
