# Generated by Django 5.0.3 on 2024-04-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0005_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='bill_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
