# Generated by Django 5.0.3 on 2024-04-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0007_remove_medicine_bill_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_number', models.BigIntegerField()),
                ('date', models.DateField()),
                ('medicine_name', models.CharField(max_length=30)),
                ('rate', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
