# Generated by Django 5.0.3 on 2024-04-25 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_patientregistration_op_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientRegistration',
        ),
    ]
