# Generated by Django 5.0.3 on 2024-04-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_number', models.IntegerField(unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('doctor', models.CharField(max_length=100)),
                ('prescription', models.TextField()),
                ('bill_amount', models.BigIntegerField(null=True)),
            ],
        ),
    ]
