# Generated by Django 5.0.3 on 2024-04-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0005_consultation_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation_details',
            name='prescription',
            field=models.TextField(null=True),
        ),
    ]
