# Generated by Django 5.0.3 on 2024-04-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0007_consultation_details_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation_details',
            name='op_number',
            field=models.IntegerField(),
        ),
    ]
