# Generated by Django 5.0.3 on 2024-04-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0009_remove_consultation_details_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation_details',
            name='op_number',
            field=models.BigIntegerField(),
        ),
    ]
