# Generated by Django 5.0.3 on 2024-04-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0010_alter_consultation_details_op_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation_details',
            name='is_consulted',
            field=models.BooleanField(default=False),
        ),
    ]
