# Generated by Django 5.0.3 on 2024-04-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0011_consultation_details_is_consulted'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation_details',
            name='bill_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
