# Generated by Django 5.1.4 on 2025-01-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0012_consultation_details_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation_details',
            name='prescription',
            field=models.JSONField(null=True),
        ),
    ]
