# Generated by Django 5.1.4 on 2025-01-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0013_alter_consultation_details_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation_details',
            name='Diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation_details',
            name='prescription',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation_details',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
